generator-settings=3;minecraft:air;127;
op-permission-level=4
allow-nether=false
level-name=practice
enable-query=false
allow-flight=false
announce-player-achievements=false
server-port=25565
level-type=FLAT
enable-rcon=false
force-gamemode=true
level-seed=
server-ip=
max-build-height=256
spawn-npcs=false
white-list=false
spawn-animals=false
hardcore=false
snooper-enabled=false
online-mode=true
resource-pack=
pvp=true
difficulty=1
enable-command-block=false
gamemode=2
player-idle-timeout=0
max-players=50
spawn-monsters=false
generate-structures=false
view-distance=8
spawn-protection=0
motd=PoppyPractice 1.8.9 NoDebuff 1v1
