config-version = "2.8"
bind = "0.0.0.0:25565"
motd = "<red>AscendingMC</red> <gray>| Lobby & Practice</gray>"
show-max-players = 100
online-mode = true
force-key-authentication = false
prevent-client-proxy-connections = false
player-info-forwarding-mode = "LEGACY"
forwarding-secret-file = "forwarding.secret"
announce-forge = false
kick-existing-players = false
ping-passthrough = "DISABLED"
enable-player-address-logging = false

[servers]
lobby = "127.0.0.1:25567"
pvp = "127.0.0.1:25566"
survival = "127.0.0.1:25568"
try = ["lobby"]

[forced-hosts]
"localhost" = ["lobby"]

[advanced]
compression-threshold = 256
compression-level = -1
login-ratelimit = 3000
connection-timeout = 5000
read-timeout = 30000
haproxy-protocol = false
tcp-fast-open = false
bungee-plugin-message-channel = true
show-ping-requests = false
failover-on-unexpected-server-disconnect = true
announce-proxy-commands = true
log-command-executions = false
log-player-connections = true
accepts-transfers = false

[query]
enabled = false
port = 25565
map = "AscendingMC"
show-plugins = false
